#!/bin/bash
if echo $( hg branches ) | grep -q -v $1; then
  echo Branch $1 doesnt exist, creating
  git branch $1
  cd ../QooxView
  git branch $1
  cd ../Gestion
fi
hg branch $1
git checkout $1
cd ../QooxView
hg branch $1
git checkout $1
