#!/bin/bash
if echo $( hg branches ) | grep -q -v $1; then
  echo Branch $1 doesnt exist, creating
  hg branch $1
  git branch $1
  cd ../QooxView
  hg branch $1
  git branch $1
  cd ../Gestion
fi
git checkout $1
cd ../QooxView
git checkout $1
