#!/bin/bash

./commit "Making branch $1"

dirs_do(){
  echo Doing -$1-
  return
  for d in AfriCompta QooxView LibNet Gestion; do
    echo Doing -$1- in $d
    cd ../$d
    $1
  done
}

if ! hg branches | grep -q "^$1 "; then
  echo HG: Branch $1 doesnt exist, creating
  dirs_do "hg branch $1"
fi
if ! git branch | grep -q "^$1 "; then
  echo Git: Branch $1 doesnt exist, creating
  dirs_do "git branch $1"
fi

dirs_do "git checkout $1"
dirs_do "hg up -C $1"

