#!/bin/bash

WDIR=$( dirname ${BASH_SOURCE[0]} )
cd $WDIR
if [ "$1" = "update" ]; then
  Binaries/gestion_update.rb
  exit
fi

echo ""
mkdir -p Backups
if [ "$( which ruby )" ]; then
  if [ ! -f /etc/gestion.conf ]; then
    if [ "$( whoami )" = "root" ]; then
      echo "Copying gestion.conf to /etc - please edit to your needs"
      BASE=$( pwd | sed -e "s/.Gestion$//" )
      sed -e "s:.opt.profeda:$BASE:" gestion.conf > /etc/gestion.conf
    else
      echo "Not started as root, doing nothing"
    fi
  fi
  if [ ! -e Diplomas ]; then
    cp -a Diplomas.src Diplomas
  fi
  if [ -f dorestore ]; then
    RESTORE=restore_$( date +%Y-%m-%d_%H.%M.%S )
    for d in data config.yaml Exas Diplomas*; do
      mv $d $RESTORE
    done
    tar xf Backups/$( cat dorestore )
    rm dorestore
  fi
  ./Gestion.rb $@
fi
echo
