#!/bin/bash

BASE=/var/www
if [ ! "$1" ]; then
  BASE=$BASE/test
fi

for a in Gestion QooxView; do
  echo Committing $a
  ssh root@solar.wifi "cd $BASE/$a; hg commit -m 'pull-all'"
done
echo Pulling Gestion
hg pull $1
hg up
echo Pulling QooxView
cd ../QooxView
hg pull $1
hg up

