#!/bin/bash

BASE=/var/www
HOST=vpn-man
if [ ! "$1" ]; then
  BASE=$BASE/test
elif [ "$1" != production ]; then
  HOST=$1
fi

echo Pushing Gestion
hg commit
hg push -f --new-branch $1
echo Pushing QooxView
cd ../QooxView
hg commit
hg push -f --new-branch $1
for a in Gestion QooxView; do
  echo Updating $a on $HOST
  ssh root@$HOST.wifi "cd $BASE/$a; hg up"
done
