#!/bin/bash

if [ ! "$1" ]; then
  echo Syntax is: $0 username
  exit 1
fi

USER=$1
ldapaddusertogroup $USER cyber_club

#if rsync -Paiv /home/$USER root@buzz.wifi:/home; then
#  exit
#else
#  exit 2
#fi
