#!/bin/bash

LED_PATH=/sys/class/leds

if [ ! "$1" -o ! "$2" ]; then
  echo "Syntax: $0 [wap|wifi|bt] wait [wait2]"
  exit 1
fi

case $1 in
bt)
  LED=dreamplug:blue:bluetooth  
  ;;
wifi)
  LED=dreamplug:green:wifi
  ;;
wap)
  LED=dreamplug:green:wifi_ap
  ;;
*)
  echo $1 is not a led
  exit 1
esac

WAIT1=$2
WAIT2=${3:-$2}

on(){
  echo 1 > $LED_PATH/$LED/brightness
}

off(){
  echo 0 > $LED_PATH/$LED/brightness
}

trap on EXIT

while sleep $WAIT1; do
  on
  sleep $WAIT2
  off
done

