#!/bin/bash
STOP=/tmp/stop_gestion

logger -s "Stopping Gestion"
touch $STOP
cd $( dirname $0 )/..
logger -s "Killing old Gestion"
pkill -f ruby.*Gestion
pkill -f tee.*gestion
logger -s "Waiting for 10 seconds"
sleep 10
logger -s "Killing old Gestion with -9"
pkill -9 -f loop_gestion
pkill -9 -f ruby.*Gestion
pkill -9 -f tee.*gestion
screen -wipe
