#!/bin/sh

if [ "$LIB_TIGO" = "loaded" ]; then
  return
fi
LIB_TIGO=loaded

. $( dirname $0 )/lib_captive
CLEFT=$LOGDIR/tigo_credit
PLEFT=$LOGDIR/tigo_promotion
DEV=/dev/ttyUSB2

ussd_encode(){
  perl -e "@a=split(//,unpack('b*',\"*$1#\")); for (\$i=7; \$i < \$#a; \$i+=8) { \$a[\$i]='' } print uc(unpack('H*', pack('b*', join('', @a))))"
}

ussd_decode(){
  perl -e "@a=split(//,unpack('b*', pack('H*',\"$1\"))); for (\$i=6; \$i < \$#a; \$i+=7) {\$a[\$i].='0' } print pack('b*', join('', @a))"
}

gcom_call(){
  comgt -s -d $DEV /etc/gcom/$1.gcom | sed -e 's/",15//'
}

get_ussd_old(){
  USSD=$( ussd_encode "$1" )
  CMD="AT+CUSD=1,$USSD,15"
  tty_send atz
  tty_send "$CMD"
  
  if [ -e $DEV ]; then
    while read rep; do log $rep; if echo $rep | grep -q "^+CUSD"; then break; fi; done < $DEV
  fi
  CUSD=$( echo $rep | sed -e "s/.*\"\(.*\)\".*/\1/" )
  REPLY=$( ussd_decode "$CUSD" )
  log "Reply is $REPLY"
  echo $REPLY
}

rs(){
  echo "$1" | grep -q "$2"
}

sms_delete(){
  if [ -e $DEV ]; then
    # Start with an empty SMS
    gnokii --deletesms SM 0 29 > /dev/null 2>&1
  fi
}

get_promotion(){
  sms_delete
  STR=$( ussd_decode $( gcom_call get_promotion ) )
  log "Got string $STR"
  if rs "$STR" Octet; then
    log Found octets
    echo $STR | sed -e "s/.*MMS, \(.*\) Octet.*/\1/"
  elif rs "$STR" "a marche"; then
    log Waiting for SMS
    if [ -e $DEV ]; then
      for w in $( seq 10 ); do
        log Waiting till $(( w * 5 )) seconds
        BYTES=$( gnokii --getsms SM 0 29 2>&1 | grep octet )
        if [ "$BYTES" ]; then
          break;
        fi
        sleep 5
      done
    fi
    sms_delete
    echo $BYTES | sed -e "s/.*MMS, \(.*\) octet.*/\1/"
  elif rs "$STR" "Vous n'avez pas"; then
    log "No promotion"
    echo 0
  fi
}

get_credit(){
  STR=$( ussd_decode $( gcom_call get_credit ) )
  log "Got credit $STR"
  if rs "$STR" solde; then
    echo $STR | sed -e "s/.*est de \([0-9]*\)\..*/\1/"
  fi
}

add_credit(){
  STR=$( get_ussd "123*$1" )
  log "Added credit $STR"
  echo $STR
}

send_credit(){
  STR=$( get_ussd "190*1234*235$2*$1" )
  log "Sent credit $2 to $1 -> $STR"
  echo $STR
}

update_credit(){
  if true; then
  log Getting credit
  C=$( get_credit )
  if [ "$C" ]; then
    echo $C | sed -e "s/\..*//" > $CLEFT
  fi
  log Getting promotion
  P=$( get_promotion ) 
  if [ "$P" ]; then
    echo $P > $PLEFT
  fi
  update_vars
  fi
}

use_credit(){
  update_vars
#  killall -9 screen
#  screen -wipe
#  screen -dmS credit /usr/bin/tigo_upc
}

update_vars(){
  CREDIT_LEFT=$( cat $CLEFT )
  PROMOTION_LEFT=$( cat $PLEFT )
}

update_vars
