#!/bin/bash

# This is a network-library that does
# - lib_captive: create and administer a captive portal
# - lib_isp: interact with ISPs - we want to have
#   - lib_isp_tigo: Tigo USB-key
#   - lib_isp_prestabist: Prestabist modem
#   - lib_isp_tawali: Tawali USB-key
#   - lib_isp_airtel: Airtel USB-key
# - lib_misc: small hacks like mail-queue and synching

# Don't need to change anything below this lines...
PWD=$( dirname $0 )
RUN=/var/run/lib-net
CONNSTAT=$RUN/connection
LOG=/var/log/lib-net
MSGS=$LOG/msgs.log
PATH=$PATH:/sbin:/usr/sbin
ACTIONLOG=$LOG/action.log
DATE=$( date +%y%m%d-%H.%M )
test -f /etc/captive.conf && . /etc/captive.conf

mkdir -p $RUN $LOG
sudo chown -R www-data.www-data $RUN $LOG

for lib in captive isp misc; do
  . $PWD/lib_$lib
done

msg() {
  date "+%F %R - $1: $2" >> $MSGS
}

log(){
  logger -- $@
}

actionlog(){
  log $@
  echo $DATE $@ >> $ACTIONLOG
}

switch_isp(){
  case "$1" in
  tigo|tawali|prestabist)
    ifdown wan
    cp /root/network.$1 /etc/config/network
    echo ISP=$1 > /etc/captive.conf
    case "$1" in
      tawali|prestabist)
      echo CONN_TYPE=always_on >> /etc/captive.conf
      ;;
    esac
    /etc/init.d/network restart
    /etc/init.d/wwan restart
    ;;
  *)
    echo ISP "$1" not available
  esac
}

restart_wwan(){
  /etc/init.d/firewall restart
  killall -9 wwan
  sort /etc/captive/aon_connected | uniq > /tmp/ac
  mv /tmp/ac /etc/captive/aon_connected
  /etc/init.d/wwan restart
}

if [ "$FUNC" ]; then
  $FUNC $@
fi

check_double_wwan(){
  WWANS=$( ps ax | grep /usr/bin/wwan | wc -l )
  if [ $WWANS -gt 2 ]; then
    actionlog Restarting wwan because it has $WWANS...
    ps ax
    #restart_wwan
  fi
}    

# Let's call an eventual function and print some variables
if [ "$1" ]; then
  VAR=""
  if [ $1 = print ]; then
    shift
    VAR=$1
    shift
  fi
  if [ "$1" = func ]; then
    shift
    FUNC=$1
    shift
    $FUNC $@
  fi
  if [ "$VAR" ]; then
    # There must be a better way to do that...
    set | grep "^$VAR=" | sed -e "s/.*=//"
  fi
fi
