#!/bin/sh

if [ "$LIB_CAPTIVE" = "loaded" ]; then
  return
fi
LIB_CAPTIVE=loaded

PWD=$( dirname $0 )
LOGDIR=/etc/captive
ACTIONLOG=$LOGDIR/action.log
USERS_CONNECTED=$LOGDIR/aon_connected
DATE=$( date +%y%m%d-%H:%M )
TTIME=$LOGDIR/time_total
. /etc/captive.conf
. $PWD/lib_$ISP

FUNC="$1"
shift

log(){
  logger -- $@
}

actionlog(){
  log $@
  echo $DATE $@ >> $ACTIONLOG
}

captive_clear(){
  iptables -t nat -F CAPTIVE
  iptables -t nat -I CAPTIVE -j RETURN
  captive_deny_ip 192.168.1.3
  captive_accept_ip 192.168.1.3
}

captive_accept_all(){
  captive_clear
  iptables -A FORWARD -j ACCEPT
  iptables -t nat -I CAPTIVE -j ACCEPT
}

captive_ip(){
  ACTION=${3:-ACCEPT}
  iptables $1 FORWARD -s $2 -j $ACTION
  iptables $1 FORWARD -d $2 -j $ACTION
  if [ ! "$3" ]; then
    iptables -t nat $1 CAPTIVE -s $2 -j $ACTION
  fi
}

captive_accept_ip(){
  captive_ip -D $1 DROP
  if iptables -L FORWARD -nv | grep -q $1; then
    actionlog "Found $1 still in iptables!"
    captive_ip -D $1
  fi
  captive_ip -I $1
}

captive_deny_ip(){
  captive_ip -D $1
  captive_ip -I $1 DROP
}

users_connected_delete(){
  grep -v $1 $USERS_CONNECTED > /tmp/uc
  mv /tmp/uc $USERS_CONNECTED
}

# This can be called from time to time to check on idle people
captive_cleanup(){
  for user in $( cat $USERS_CONNECTED.tmp ); do
    PACKETS=$( iptables -L FORWARD -nv | grep $user | tail -n 1 | sed -e "s/ *\([^ ]*\).*/\1/" )
    log Checking ip $user - has $PACKETS packets
    if [ ! "$PACKETS" ]; then
      actionlog Still in $USERS_CONNECTED, but not in iptables
      users_connected_delete $user
    elif [ "$PACKETS" = 0 ]; then
      actionlog No packets, kicking $user
      captive_deny_ip $user
      users_connected_delete $user
    fi
  done
#  log Clearing counters
  iptables -Z FORWARD
  cp $USERS_CONNECTED $USERS_CONNECTED.tmp
}

connection_restart(){
  if [ "$CONN_TYPE" = "always_on" ]; then
    ifdown wan
    ifup wan
    if [ -f $USERS_CONNECTED ]; then
      rm -f $USERS_CONNECTED
    fi
    forward_clear
    forward_accept
  fi
}

switch_isp(){
  case "$1" in
  tigo|tawali|prestabist)
    ifdown wan
    cp /root/network.$1 /etc/config/network
    echo ISP=$1 > /etc/captive.conf
    case "$1" in
      tawali|prestabist)
      echo CONN_TYPE=always_on >> /etc/captive.conf
      ;;
    esac
    /etc/init.d/network restart
    /etc/init.d/wwan restart
    ;;
  *)
    echo ISP "$1" not available
  esac
}

restart_wwan(){
  /etc/init.d/firewall restart
  killall -9 wwan
  sort /etc/captive/aon_connected | uniq > /tmp/ac
  mv /tmp/ac /etc/captive/aon_connected
  /etc/init.d/wwan restart
}

if [ "$FUNC" ]; then
  $FUNC $@
fi
