#!/bin/bash

. $( dirname $0 )/lib_backup
DATE=$1

#sleep 2
#touch /tmp/stop_gestion
#$WDIR/Binaries/kill_gestion
#sleep 2

systemctl stop gestion
sleep 5
touch /tmp/stop_gestion
$WDIR/Binaries/kill_gestion
echo Going to restore $BACKUP_DIR/$DATE > /tmp/restore
tar -C /var/lib/gestion -Pxzf $BACKUP_DIR/$DATE

sleep 5
systemctl start gestion

#$WDIR/Binaries/start_gestion
