#!/bin/bash

cd $( dirname $0 )/..

log(){
  echo $( date ) $@ >> $LOG
}

biglog(){
  echo "

            ****            ****            ****            ****
$( date )
            ****            ****            ****            ****

" >> $LOG
}

LOG=/var/log/gestion.log
if ! touch $LOG; then
  LOG=gestion.log
fi
STOP=/tmp/stop_gestion
rm $STOP
while [ ! -f $STOP ]; do
  now=$( date +%s )
  ./Gestion.rb 2>&1 | tee -a $LOG
  biglog Oups - quit Gestion after $(( quit - now )) seconds
  quit=$( date +%s )
  if [ $(( quit - now )) -lt 60 ]; then
    log This seems to be quite bad... not restarting >> $LOG
    tail -n 30 $LOG | mail -s "Gestion crashed on short notice" ineiti@profeda.org
    exit
  fi
done
biglog Stopped because of $STOP >> $LOG
