#!/bin/bash

. /etc/environment
export LANG
export LC_ALL
date >> /var/log/start_gestion
set >> /var/log/start_gestion
logger -s "Starting Gestion"
sleep 2
cd $( dirname $0 )/..
if pgrep -f ruby.*Gestion; then
  Binaries/kill_gestion
fi
logger -s "Starting new Gestion"
screen -S Gestion -d -m Binaries/loop_gestion
