#!/bin/bash

WDIR=$( dirname ${BASH_SOURCE[0]} )

if [ "$1" = "-f" ]; then
  shift
  $WDIR/kill_gestion
  sleep 2
  mv $WDIR/../data /var/tmp/data.$( date +%s )
  if [ "$1" ]; then
    $WDIR/restore $1
  else
    $WDIR/start_gestion
  fi
else
  echo Not doing swipe - use the '-f' parameter
  exit 1
fi
