#!/bin/bash
# With an argument we try to get a promotion, else we just show what's left
if [ "$1" ]; then
  PROMOTION=""
  case "$1" in
  hour|30MB)
    PROMOTION=1111
    ;;
  day|100MB)
    PROMOTION=2424
    ;;
  week|1GB)
    PROMOTION=7777
    ;;
  month|5GB)
    PROMOTION=3030
    ;;
  esac
  if [ "$PROMOTION" ]; then
    # Testing for new version which has a global config-file
    if [ -f /etc/gammu.conf ]; then
      gammu sendsms TEXT $PROMOTION -text "kattir" 2>/dev/null
    else
      echo kattir | gammu sendsms TEXT $PROMOTION 2>/dev/null
    fi
  fi
fi

sleep 10

BYTES_LEFT=$( gsm-ussd -m /dev/ttyUSB2 --no-cleartext '*128#' 2>/dev/null | sed -e "s/.*MMS, \(.*\) .ctet.*/\1/" )
if echo $BYTES_LEFT | grep -q "Vous n'avez" -; then
  BYTES_LEFT=0
fi
